apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hallo-world-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/FIIRLEBR/HelloWorldWebApp.git
    targetRevision: HEAD
    path: .
  destination: 
    server: https://kubernetes.default.svc
    namespace: master

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
