apiVersion: apps/v1
kind: Deployment
metadata:
  name: hallo-world-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hallo-world
  template:
    metadata:
      labels:
        app: hallo-world
    spec:
      containers:
      - name: hallo-world
        image: fsn1980/hallo_world_app:1.0.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
